/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pw2OKrbJNhK
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Signup() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-center">Create an account</CardTitle>
        <CardDescription className="text-center">
          Start your free trial today.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-4">
          <Label htmlFor="name">Name</Label>
          <Input
            autoComplete="name"
            id="name"
            placeholder="Elise Stevens"
            type="text"
          />
        </div>
        <div className="space-y-4">
          <Label htmlFor="email">Email</Label>
          <Input
            autoComplete="email"
            id="email"
            placeholder="elise@example.com"
            type="email"
          />
        </div>
        <div className="space-y-4">
          <Label htmlFor="password">Password</Label>
          <Input autoComplete="new-password" id="password" type="password" />
        </div>
        <Button className="w-full" type="submit">
          Sign Up
        </Button>
      </CardContent>
    </Card>
  );
}
